JobBoard/JobBoard/Models/Job/CustomValidation/ValidateFechaExpiracionAttribute.cs
using JobBoard.Models.Job.Input;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobBoard.Models.Job.CustomValidation
{
    public class ValidateFechaExpiracionAttribute : ValidationAttribute
    {
        /// <summary>
        /// Valida el tipo de documento ingresado
        /// </summary>
        /// <param name="value"></param>
        /// <param name="validationContext"></param>
        /// <returns></returns>
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            DateTimeOffset fechaValida = DateTime.Now.Date;
            DateTimeOffset fechaEnviada = Convert.ToDateTime(value.ToString()).AddHours(23).AddMinutes(59);

            if (fechaEnviada < fechaValida)
            {
                    return new ValidationResult(
                        $"La fecha de expiracion debe ser mayor o igual al dia actual", new[] { nameof(JobInputViewModel.FechaExpiracionJob) });
            }

            return ValidationResult.Success;
        }
    }
}

JobBoard/JobBoard/Models/Job/Input/FiltrosJobInputViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobBoard.Models.Job.Input
{
    /// <summary>
    /// Filtros del listado
    /// </summary>
    public class FiltrosJobInputViewModel
    {
        /// <summary>
        /// Titulo
        /// </summary>
        public string FiltroTitulo { get; set; }

        /// <summary>
        /// Fecha de inicio de expiracion
        /// </summary>
        public string FechaExpiracionInicio { get; set; }

        /// <summary>
        /// Fecha fin de expiracion
        /// </summary>
        public string FechaExpiracionFin { get; set; }
    }
}

JobBoard/JobBoard/Models/Job/Input/JobInputViewModel.cs
using JobBoard.Models.Job.CustomValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobBoard.Models.Job.Input
{
    /// <summary>
    /// Maneja los datos de job 
    /// </summary>
    public class JobInputViewModel
    {
        public JobInputViewModel()
        {
            Codigo = null;
        }
        /// <summary>
        /// Codigo
        /// </summary>
        public Guid? Codigo { get; set; }
        /// <summary>
        /// Titulo del trabajo
        /// </summary>
        [Required(ErrorMessage = "El titulo es requerido")]
        [MaxLength(256,ErrorMessage = "La cantidad maxima de caracteres es de 256")]
        public string Titulo { get; set; }

        /// <summary>
        /// Descripcion del trabajo
        /// </summary>
        [Required(ErrorMessage = "La descripcion es requerida")]
        [MaxLength(1500, ErrorMessage = "La cantidad maxima e caracteres es de 1500")]
        public string Descripcion { get; set; }

        /// <summary>
        /// Fecha de expiracion del trabajo
        /// </summary>
        [Required(ErrorMessage = "La fecha de expiracion es requerido")]
        [ValidateFechaExpiracionAttribute]
        public string FechaExpiracionJob { get; set; }
    }
}

JobBoard/JobBoard/Models/Job/Output/ListaJobOutputViewModel.cs
using JobBoard.Models.Job.Input;
using JobBoard.Models.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobBoard.Models.Job.Output
{
    /// <summary>
    /// Datos necesarios para render la vista
    /// </summary>
    public class ListaJobOutputViewModel
    {
        /// <summary>
        /// Filtros
        /// </summary>
        public FiltrosJobInputViewModel Filtros { get; set; }

        /// <summary>
        /// Listado de job
        /// </summary>
        public List<JobBoard.Core.Model.Job> ListadoJob{ get; set; }

        /// <summary>
        /// paginacion
        /// </summary>
        public PagingInfo PagingInfo { get; set; }
    }
}

JobBoard/JobBoard/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobBoard.Core.DTO;
using JobBoard.Core.DTO.Job.Input;
using JobBoard.Core.Service;
using JobBoard.Extensions;
using JobBoard.Models.Job.Input;
using JobBoard.Models.Job.Output;
using Microsoft.AspNetCore.Mvc;

namespace JobBoard.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobService _jobService;
        public readonly int _cantidadPorPagina;

        public JobController(IJobService jobService)
        {
            _jobService = jobService;
            _cantidadPorPagina = 20;
        }

        public async Task<IActionResult> Index(FiltrosJobInputViewModel filtros, int page = 1)
        {
            if (filtros == null)
                filtros = new FiltrosJobInputViewModel();

            ListaJobOutputViewModel listaJobOutputViewModel = await GetJobsVM(filtros, page);
            return View(listaJobOutputViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetJob(Guid? codigo)
        {
            JobInputViewModel jobInputViewmodel = new JobInputViewModel();

            if (codigo != null)
            {
                JobBoard.Core.Model.Job Job = await _jobService.GetJob(codigo.Value);
                jobInputViewmodel = new JobInputViewModel()
                {
                    Codigo = Job.Codigo,
                    Descripcion = Job.Descripcion,
                    Titulo = Job.Titulo,
                    FechaExpiracionJob = Job.FechaExpiracion.ToString("dd/MM/yyyy")
                };
            }

            string html = await this.RenderViewAsync("_DetalleJob", jobInputViewmodel);
            return Json(new { existoso = true, html = html });
        }

        [HttpPost]
        public async Task<IActionResult> GuardarJob(JobInputViewModel jobInputViewModel, FiltrosJobInputViewModel filtros, int page)
        {
            if (!ModelState.IsValid)
            {
                string htmlDocumento = await this.RenderViewAsync("_DetalleJob", jobInputViewModel);
                return Json(new { existoso = false, html = htmlDocumento });
            }

            if (jobInputViewModel.Codigo == null)
                await _jobService.AddNewJob(new NewJobInputDto()
                {
                    Descripcion = jobInputViewModel.Descripcion,
                    Titulo = jobInputViewModel.Titulo,
                    FechaExpiracion = Convert.ToDateTime(jobInputViewModel.FechaExpiracionJob)
                });

            if (jobInputViewModel.Codigo != null)
                await _jobService.Editjob(new EditJobInputDto()
                {
                    Codigo = jobInputViewModel.Codigo.Value,
                    Descripcion = jobInputViewModel.Descripcion,
                    Titulo = jobInputViewModel.Titulo,
                    FechaExpiracion = Convert.ToDateTime(jobInputViewModel.FechaExpiracionJob)
                });

            ListaJobOutputViewModel listaJobOutputViewModel = await GetJobsVM(filtros, page);
            string html = await this.RenderViewAsync("_ListaJob", listaJobOutputViewModel);
            return Json(new { existoso = true, html = html });
        }



        [HttpPost]
        public async Task<IActionResult> EliminarJob(Guid idJob, FiltrosJobInputViewModel filtros)
        {
            await _jobService.DeleteJob(idJob);
            ListaJobOutputViewModel listaJobOutputViewModel = await GetJobsVM(filtros, 1);
            string html = await this.RenderViewAsync("_ListaJob", listaJobOutputViewModel);
            return Json(new { existoso = true, html = html });
        }


        /// <summary>
        /// Crea un viewmodel el cual contiene todos los datos necesarios para mostrar en la vista
        /// </summary>
        /// <param name="filtros"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        private async Task<ListaJobOutputViewModel> GetJobsVM(FiltrosJobInputViewModel filtros, int page)
        {
            DateTimeOffset fechaFin =
                string.IsNullOrEmpty(filtros.FechaExpiracionFin) ? DateTimeOffset.Now.AddMonths(3) : Convert.ToDateTime(filtros.FechaExpiracionFin);

            DateTimeOffset fechaInicio =
               string.IsNullOrEmpty(filtros.FechaExpiracionInicio) ? DateTimeOffset.Now.AddMonths(-3) : Convert.ToDateTime(filtros.FechaExpiracionInicio);

            filtros.FechaExpiracionFin = fechaFin.ToString("dd/MM/yyyy");
            filtros.FechaExpiracionInicio = fechaInicio.ToString("dd/MM/yyyy");

            FiltrosJobInputDto filtrosJobInputDto = new FiltrosJobInputDto()
            {
                FechaExpiracionFin = fechaFin,
                FechaExpiracionInicio = fechaInicio,
                Titulo = filtros.FiltroTitulo
            };

            ResultadoPaginadoDTO<JobBoard.Core.Model.Job> resultado =
                await _jobService.ListadoPaginadoJobAsync(filtrosJobInputDto, _cantidadPorPagina, page);


            ListaJobOutputViewModel listadoJobVm = new ListaJobOutputViewModel()
            {
                Filtros = filtros,
                ListadoJob = resultado.Resultado,
                PagingInfo = new Models.Paging.PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = _cantidadPorPagina,
                    TotalItems = resultado.CantidadTotal
                }
            };

            return listadoJobVm;
        }

    }
}

JobBoard/JobBoard/ViewComponents/PaginacionViewComponent.cs
using JobBoard.Models.Paging;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobBoard.ViewComponents
{
    public class PaginacionViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke(PagingInfo pagingInfo, Func<int, string> pageUrl, string clasePersonalizada = null)
        {
            PagingVm model = new PagingVm()
            {
                PaginaActiva = pagingInfo.CurrentPage,
                Botones = new List<BotonPaginacionVm>(),
                ClasePersonalizada = clasePersonalizada
            };
            int totalP = 10;
            int ipage = 1;

            //Pagina anterior
            if (pagingInfo.CurrentPage > 1)
            {
                model.UrlPaginaAnterior = pageUrl(pagingInfo.CurrentPage - 1);
            }

            if (totalP > pagingInfo.TotalPages)
                totalP = pagingInfo.TotalPages;

            if (pagingInfo.CurrentPage > 6)
            {
                totalP = pagingInfo.CurrentPage + 4;
                ipage = pagingInfo.CurrentPage - 5;

                if (totalP > pagingInfo.TotalPages)
                {
                    totalP = pagingInfo.TotalPages;
                    ipage = pagingInfo.TotalPages - 9;
                    if (ipage < 1)
                    {
                        ipage = 1;
                    }

                }
            }

            if (totalP != 1)
            {
                for (int i = ipage; i <= totalP; i++)
                {
                    model.Botones.Add(new BotonPaginacionVm()
                    {
                        Pagina = i,
                        UrlBoton = pageUrl(i)
                    });
                }
            }


            //Pagina siguiente
            if (pagingInfo.CurrentPage < pagingInfo.TotalPages)
            {
                model.UrlPaginaSiguiente = pageUrl(pagingInfo.CurrentPage + 1);
            }

            return View(model);
        }
    }
}

JobBoard/JobBoard/Views/Job/Index.cshtml
@model JobBoard.Models.Job.Output.ListaJobOutputViewModel
@{
    ViewData["Title"] = "Lista de job";
}
<div class="wrapper wrapper-content px-0 py-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content p-3 px-md-4">
                        <div class="row-b4 align-items-end">
                            <div class="col-md">
                                <h1 class="mb-3">Lista de jobs</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ibox">
            <div class="ibox-content pt-3">
                <fieldset class="filtros">
                    <legend>Filtrar resultados</legend>
                    <form asp-controller="Job" asp-action="Index" method="get" id="frm-filtros">
                        <div class="row-b4 align-items-end">
                            <div class="col-lg">
                                <div class="row-b4 align-items-end">
                                    <div class="col-md-4 col-lg-3 form-group">
                                        <label>Titulo</label>
                                        <input asp-for="@Model.Filtros.FiltroTitulo" type="text" class="form-control">
                                    </div>
                                    <div class="col-md-4  form-group">
                                        <label>Fecha de expiracion desde :</label>
                                        <div class="input-group date">
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                            <input asp-for="@Model.Filtros.FechaExpiracionInicio" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-3  form-group">
                                        <label>Hasta :</label>
                                        <div class="input-group date">
                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                            <input asp-for="@Model.Filtros.FechaExpiracionFin" type="text" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-lg-3">
                                        <div class="form-group">
                                            <button style="margin-top:10px" class="btn btn-primary">Aplicar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <br />
                </fieldset>

                <div class="form-group">
                    <div>
                        <a class="btn btn-primary getjob" data-codigo=""  href="@Url.Action("GetJob","Job")" >Nuevo</a>
                    </div>
                </div>
                <br />
                <div id="ListadoJobs">
                    @await Html.PartialAsync("_ListaJob", Model)
                </div>

            </div>
        </div>
    </div>
</div>

<div class="modal inmodal fade" id="modal-detalle" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" id="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
                <h4 class="modal-title">Detalle de job</h4>
            </div>
            <div class="modal-body">
                <div id="formjob">

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(document).ready(function () {

            $(document).on('click', ".getjob", function (e) {

            Bitworks.Ventanas.mostrarLoading();
            var codigo = $(this).data('codigo');
            e.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                type: 'GET',
                data: { codigo: codigo},
                success: function (result) {
                    if (result.existoso) {
                        $("#formjob").html('');
                        $("#formjob").html(result.html);
                        $.validator.unobtrusive.parse("#frmguardarjob");
                        RefreshInputDate();
                        Bitworks.Ventanas.ocultarLoading();
                        $("#modal-detalle").modal();

                    } else {
                        swal("Error", "'Error al intentar hacer la peticion recarge la pagina y vuelva a intentarlo", "error");
                    }
                },
                error: function (error) {
                    swal("Error", "Error al intentar hacer la peticion recarge la pagina y vuelva a intentarlo", "error");
                }
            });

        });

            $(document).on('submit', '#frmguardarjob', function (e) {

            Bitworks.Ventanas.mostrarLoading();
            e.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: $(this).serialize() +"&"+ $("#frm-filtros").serialize() + "&page=" + $("#paginaactual").val(),
                success: function (result) {
                    if (result.existoso) {
                        $("#modal-detalle").modal("hide");
                        $("#ListadoJobs").html('');
                        $("#ListadoJobs").html(result.html);
                        swal("Exito", "job guardado correctamente", "success");
                    } else {
                        $("#formjob").html('');
                        $("#formjob").html(result.html);
                        $.validator.unobtrusive.parse("#frmguardarjob");
                        RefreshInputDate();
                        Bitworks.Ventanas.ocultarLoading();
                    }
                },
                error: function (error) {
                    swal("Error", "Error al intentar hacer la peticion recarge la pagina y vuelva a intentarlo", "error");
                }
            });
      });

            $(document).on('click', ".eliminarJob", function (e) {

                e.preventDefault();
                var $this = $(this);
                var codigo = $this.data("codigo");
                var filtros = $("#frm-filtros").serialize();
                Bitworks.Ventanas.mostrarLoading();
                $.ajax({
                    url: $this.attr('href'),
                    type: 'POST',
                    data: "idJob=" + codigo + "&" + filtros,
                    success: function (result) {
                        if (result.existoso) {
                            $("#ListadoJobs").html('');
                            $("#ListadoJobs").html(result.html);
                            swal("Exito", "Job eliminado correctamente", "success");

                        } else {
                            swal("Error", "Error al intentar hacer la peticion recarge la pagina y vuelva a intentarlo", "error");
                        }
                    },
                    error: function (error) {
                        swal("Error", "Error al intentar hacer la peticion recarge la pagina y vuelva a intentarlo", "error");
                    }
                });

        });

            function RefreshInputDate(){
                $('.input-group.date').datepicker({
                    format: 'dd/mm/yyyy',
                    todayBtn: "linked",
                    keyboardNavigation: false,
                    forceParse: false,
                    calendarWeeks: true,
                    autoclose: true,
                    constrainInput: false
                });
                $('.input-group.date input').attr('readonly', true);
        }
 })
    </script>
}

JobBoard/JobBoard/Views/Job/_DetalleJob.cshtml
@model JobBoard.Models.Job.Input.JobInputViewModel
@{
    Layout = null;
}

<form asp-action="GuardarJob" asp-controller="Job" method="post" id="frmguardarjob">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input type="hidden" asp-for="Codigo" />

    <div class="modal-body">
        <div class="row">

            <div class="form-group col-md-12" style="margin-bottom:5px!important">
                <label asp-for="Titulo">Titulo</label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger small form-text"></span>

            </div>
            <div class="form-group col-md-12" style="margin-bottom:5px!important">
                <label asp-for="FechaExpiracionJob">Fecha de expiracion</label>
                <div class="input-group date">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    <input asp-for="FechaExpiracionJob" type="text" class="form-control">
                </div>
                <span asp-validation-for="FechaExpiracionJob" class="text-danger small form-text"></span>
            </div>
            <div class="form-group col-md-12" style="margin-bottom:5px!important">
                <label asp-for="Descripcion">Descripcion</label>
                <textarea asp-for="Descripcion" class="form-control" rows="5" cols="4">@Model.Descripcion</textarea>
                <span asp-validation-for="Descripcion" class="text-danger small form-text"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary" id="btn-guardar">Guardar</button>
        <button type="button" class="btn btn-default btn-white" data-dismiss="modal">Cerrar</button>
    </div>
</form>

JobBoard/JobBoard/Views/Job/_ListaJob.cshtml
@model JobBoard.Models.Job.Output.ListaJobOutputViewModel
@{
    Layout = null;
    Func<int, string> urlPaginacion = pag => Url.Action("Index", "Job", new
    {
        Page = pag,
        @FiltroTitulo = Model.Filtros.FiltroTitulo,
        @FechaExpiracionInicio = Model.Filtros.FechaExpiracionInicio,
        @FechaExpiracionFin = Model.Filtros.FechaExpiracionFin
    });
}

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Fecha de expiracion</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (JobBoard.Core.Model.Job job in Model.ListadoJob)
            {
            <tr>
                <td>@job.Titulo</td>
                <td>@job.FechaExpiracion.ToString("dd/MM/yyyy")</td>
                <td> <a class="btn btn-white getjob" data-codigo="@job.Codigo" asp-action="GetJob" asp-controller="Job"><i class="fa fa-pencil"></i> Editar</a></td>

                <td> <a class="btn btn-white eliminarJob" data-codigo="@job.Codigo" asp-action="EliminarJob" asp-controller="Job"><i class="fa fa-trash"></i> Eliminar</a></td>

            </tr>
            }
        </tbody>
    </table>
    <div class="mb-md-4 py-5" style="text-align:center;">
        <input type="hidden" value="@Model.PagingInfo.CurrentPage" id="paginaactual" />
        @await Component.InvokeAsync("Paginacion", new { pagingInfo = Model.PagingInfo, pageUrl = urlPaginacion })
    </div>
</div>